### PR TITLE
setup: Install python2

### PR DESCRIPTION
**Pull request by NotZeetaa**
* Fixes errors for some kernels that create dtbo using python2

### CODE REVIEW

**Comment by Tashar02** [comment]
Reword commit message bruh.

**Review by ElectroPerf — APPROVED** [review]

**Comment by Tashar02** [comment]
`Fixes errors for some kernels that create dtbo using python2`

**Comment by NotZeetaa** [comment]
> `Fixes errors for some kernels that create dtbo using python2`

Ok

**Comment by Tashar02** [comment]
amend the commit and fpush and pull request can get the new commit

**Comment by Tashar02** [comment]
Thanks

**Comment by Divyanshu-Modi** [comment]
@NotZeetaa Update ur  python2 tool to python3

**Pull request merged**
