### PR TITLE
setup: Install python2

### PR DESCRIPTION
**Pull request by NotZeetaa**
* Fixes errors for some kernel who creates dtbo with python2

### CODE REVIEW

**Review by ElectroPerf — APPROVED** [review]

**Comment by Tashar02** [comment]
uhh, why we changing docker now?

**Comment by NotZeetaa** [comment]
> uhh, why we changing docker now?

Ignore
How i can nuke the second cummit

**Comment by tattwamashi** [comment]
For fuck sake github.. fix your dumb pul requests

**Comment by tattwamashi** [comment]
@ElectroPerf s/pul/pull

**Comment by tattwamashi** [comment]
Kys, wtf github bot in tg  dumbass

**Pull request closed without merging**
